# Generated by Django 6.0.3 on 2026-05-01 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Livres', '0001_initial'),
        ('Livreurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCommande', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='en_attente', max_length=50)),
                ('modePaiement', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Clients.client')),
                ('livres', models.ManyToManyField(related_name='commandes', to='Livres.livre')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='Livreurs.livreur')),
            ],
            options={
                'db_table': 'commandes',
            },
        ),
    ]
