# Generated by Django 6.0.3 on 2026-05-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Livres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('datePaiement', models.DateField(auto_now_add=True)),
                ('methode', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Clients.client')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Livres.livre')),
            ],
            options={
                'db_table': 'paiements',
            },
        ),
    ]
