# Generated by Django 6.0.3 on 2026-05-01 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Livres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmprunt', models.DateField(auto_now_add=True)),
                ('dateRetourPrevue', models.DateField()),
                ('dateRetourReelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rendu', 'Rendu'), ('en_retard', 'En retard')], default='en_cours', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='Clients.client')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='Livres.livre')),
            ],
            options={
                'db_table': 'emprunts',
            },
        ),
    ]
