# Generated by Django 6.0.3 on 2026-05-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utilisateurs.utilisateur')),
            ],
            options={
                'db_table': 'administrateurs',
            },
            bases=('Utilisateurs.utilisateur',),
        ),
    ]
