# Generated by Django 6.0.3 on 2026-05-06 09:52

from django.db import migrations


def finalize_administrateurs_table(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute('ALTER TABLE administrateurs DROP PRIMARY KEY')
        cursor.execute('ALTER TABLE administrateurs ADD COLUMN id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST')
        cursor.execute('ALTER TABLE administrateurs DROP COLUMN utilisateur_ptr_id')


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateurs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(finalize_administrateurs_table, migrations.RunPython.noop),
    ]
