# Generated by Django 6.0.3 on 2026-05-01 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utilisateurs.utilisateur')),
                ('adresse', models.CharField(max_length=255)),
                ('dateInscription', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clients',
            },
            bases=('Utilisateurs.utilisateur',),
        ),
    ]
