# Generated by Django 6.0.3 on 2026-05-06 09:52

from django.db import migrations


def finalize_clients_table(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute('ALTER TABLE clients DROP PRIMARY KEY')
        cursor.execute('ALTER TABLE clients ADD COLUMN id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST')
        cursor.execute('ALTER TABLE clients ADD COLUMN nom VARCHAR(100) NULL')
        cursor.execute('ALTER TABLE clients ADD COLUMN prenom VARCHAR(100) NULL')
        cursor.execute('ALTER TABLE clients ADD COLUMN email VARCHAR(191) NULL')
        cursor.execute('ALTER TABLE clients ADD COLUMN motDePasse VARCHAR(255) NULL')
        cursor.execute('ALTER TABLE clients ADD COLUMN telephone VARCHAR(20) NULL')
        cursor.execute(
            'UPDATE clients c JOIN utilisateurs u ON c.utilisateur_ptr_id = u.id '
            'SET c.nom = u.nom, c.prenom = u.prenom, c.email = u.email, c.motDePasse = u.motDePasse, c.telephone = u.telephone'
        )
        cursor.execute('ALTER TABLE clients MODIFY COLUMN nom VARCHAR(100) NOT NULL')
        cursor.execute('ALTER TABLE clients MODIFY COLUMN prenom VARCHAR(100) NOT NULL')
        cursor.execute('ALTER TABLE clients MODIFY COLUMN email VARCHAR(191) NOT NULL')
        cursor.execute('ALTER TABLE clients MODIFY COLUMN motDePasse VARCHAR(255) NOT NULL')
        cursor.execute('ALTER TABLE clients MODIFY COLUMN telephone VARCHAR(20) NOT NULL')
        cursor.execute('ALTER TABLE clients ADD UNIQUE INDEX clients_email_unique (email)')
        cursor.execute('ALTER TABLE clients DROP COLUMN utilisateur_ptr_id')


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(finalize_clients_table, migrations.RunPython.noop),
    ]
