# Generated by Django 6.0.3 on 2026-05-01 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Livres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReservation', models.DateField(auto_now_add=True)),
                ('dateExpiration', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='active', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Clients.client')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Livres.livre')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
