# Generated by Django 6.0.3 on 2026-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('motDePasse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'utilisateurs',
            },
        ),
    ]
