# Generated by Django 6.0.3 on 2026-05-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
        ('Clients', '0002_remove_client_utilisateur_ptr_client_email_client_id_and_more'),
        ('Livreurs', '0002_remove_livreur_utilisateur_ptr_livreur_email_and_more'),
        ('Administrateurs', '0002_remove_administrateur_utilisateur_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
