# Generated by Django 6.0.3 on 2026-05-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('anneePublication', models.IntegerField()),
                ('langue', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('Nom_Auteur', models.CharField(max_length=100)),
                ('prixOriginal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_symbolique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='Categories.categorie')),
            ],
            options={
                'db_table': 'livres',
            },
        ),
    ]
