# Generated by Django 6.0.3 on 2026-05-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('motDePasse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('vehicule', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('en_livraison', 'En livraison')], default='disponible', max_length=20)),
            ],
            options={
                'db_table': 'livreurs',
            },
        ),
    ]
