# Generated by Django 6.0.3 on 2026-05-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Utilisateurs.utilisateur')),
                ('vehicule', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('en_livraison', 'En livraison')], default='disponible', max_length=20)),
            ],
            options={
                'db_table': 'livreurs',
            },
            bases=('Utilisateurs.utilisateur',),
        ),
    ]
