# Generated by Django 6.0.3 on 2026-05-06 09:52

from django.db import migrations


def finalize_livreurs_table(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute('ALTER TABLE livreurs DROP PRIMARY KEY')
        cursor.execute('ALTER TABLE livreurs ADD COLUMN id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST')
        cursor.execute('ALTER TABLE livreurs ADD COLUMN nom VARCHAR(100) NULL')
        cursor.execute('ALTER TABLE livreurs ADD COLUMN prenom VARCHAR(100) NULL')
        cursor.execute('ALTER TABLE livreurs ADD COLUMN email VARCHAR(191) NULL')
        cursor.execute('ALTER TABLE livreurs ADD COLUMN motDePasse VARCHAR(255) NULL')
        cursor.execute('ALTER TABLE livreurs ADD COLUMN telephone VARCHAR(20) NULL')
        cursor.execute(
            'UPDATE livreurs l JOIN utilisateurs u ON l.utilisateur_ptr_id = u.id '
            'SET l.nom = u.nom, l.prenom = u.prenom, l.email = u.email, l.motDePasse = u.motDePasse, l.telephone = u.telephone'
        )
        cursor.execute('ALTER TABLE livreurs MODIFY COLUMN nom VARCHAR(100) NOT NULL')
        cursor.execute('ALTER TABLE livreurs MODIFY COLUMN prenom VARCHAR(100) NOT NULL')
        cursor.execute('ALTER TABLE livreurs MODIFY COLUMN email VARCHAR(191) NOT NULL')
        cursor.execute('ALTER TABLE livreurs MODIFY COLUMN motDePasse VARCHAR(255) NOT NULL')
        cursor.execute('ALTER TABLE livreurs MODIFY COLUMN telephone VARCHAR(20) NOT NULL')
        cursor.execute('ALTER TABLE livreurs ADD UNIQUE INDEX livreurs_email_unique (email)')
        cursor.execute('ALTER TABLE livreurs DROP COLUMN utilisateur_ptr_id')


class Migration(migrations.Migration):

    dependencies = [
        ('Livreurs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(finalize_livreurs_table, migrations.RunPython.noop),
    ]
